#测试进度样本架页面时间
import pyautogui
print(pyautogui.size())
#进入进度页面
jinduX=411
jinduY=156
pyautogui.moveTo(jinduX,jinduY,0.5)
pyautogui.click(jinduX,jinduY)
#进入样本架页面
yangbenjiaX=127
yangbenjiaY=352
pyautogui.moveTo(yangbenjiaX,yangbenjiaY,0.5)
pyautogui.click(yangbenjiaX,yangbenjiaY)
#样本时间区间1点击
shijianX1=629
shijainY1=298
pyautogui.moveTo(shijianX1,shijainY1,0.5)
pyautogui.click(shijianX1,shijainY1)
#样本时间区间2点击
shijianX2=853
shijianY2=298
pyautogui.moveTo(shijianX2,shijianY2,0.5)
pyautogui.click(shijianX2,shijianY2)
#点击选择当日点击
dianjidangtianriqiX=
dianjidangtianriqiY=
pyautogui.moveTo(dianjidangtianriqiX,dianjidangtianriqiY,0.5)
pyautogui.click(dianjidangtianriqiX,dianjidangtianriqiY)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          njidangtianriqiY)
#点击年按钮
dianjinianannuiX=
dianjinianannuiY=
pyautogui.moveTo(dianjinianannuiX,dianjinianannuiY,0.5)
pyautogui.click(dianjinianannuiX,dianjinianannuiY)
#搜索年加按钮
#年增加按钮
nianzengjiaannuiX=
nianjianxiaoannuiY=
pyautogui.moveTo(nianzengjiaannuiX,nianjianxiaoannuiY,0.5)
pyautogui.click(nianzengjiaannuiX,nianjianxiaoannuiY)
#月增加按钮
yuezengjiaannuiX=
yuejianxiaoannuiY=
pyautogui.moveTo(yuezengjiaannuiX,yuejianxiaoannuiY,0.5)
pyautogui.click(yuezengjiaannuiX,yuejianxiaoannuiY)
#月减少按钮
yuejianxiaoannuiX=
yuejianxiaoannuiY=
pyautogui.moveTo(yuezengjiaannuiX,yuejianxiaoannuiY,0.5)
pyautogui.click(yuejianxiaoannuiX,yuejianxiaoannuiY)

