import time

import pyautogui
#进入模块页面
mokuaiX=
mokuaiY=
pyautogui.moveTo()
pyautogui.click()
#点击进样回收停止按钮
jinyanghuishoutingzhiannuiX=
jinyanghuishoutingzhiannuiY=
pyautogui.moveTo(jinyanghuishoutingzhiannuiX,jinyanghuishoutingzhiannuiY,0.5)
pyautogui.click(jinyanghuishoutingzhiannuiX,jinyanghuishoutingzhiannuiY)
#点击转换停止按钮
zhuanhuantingzhiannuiX=
zhuanhuantingzhianuiY=
pyautogui.moveTo(zhuanhuantingzhiannuiX,zhuanhuantingzhianuiY,0.5)
pyautogui.click(zhuanhuantingzhiannuiX,zhuanhuantingzhianuiY)
#点击凝血仪1停止按钮
ningxueyi1tingzhiannuiX=
ningxueyi1tingzhiannuiY=
pyautogui.moveTo(ningxueyi1tingzhiannuiX,ningxueyi1tingzhiannuiY,0.5)
#点击凝血仪2停止按钮
ningxueyi1tingzhiannui2X=
ningxueyi1tingzhiannui2Y=
pyautogui.moveTo(ningxueyi1tingzhiannui2X,ningxueyi1tingzhiannui2Y,0.5)
pyautogui.click(ningxueyi1tingzhiannui2X,ningxueyi1tingzhiannui2Y)
#点击凝血仪3停止按钮
ningxueyi1tingzhiannui3X=
ningxueyi1tingzhiannui3Y=
pyautogui.moveTo(ningxueyi1tingzhiannui3X,ningxueyi1tingzhiannui3Y,0.5)
pyautogui.click(ningxueyi1tingzhiannui3X,ningxueyi1tingzhiannui3Y)
#点击缓存区模块停止按钮
huancunqutingzhiannuiX=
huancunqutingzhiannuiY=
pyautogui.moveTo(huancunqutingzhiannuiX,huancunqutingzhiannuiY,0.5)
pyautogui.click(huancunqutingzhiannuiX,huancunqutingzhiannuiY)
#中间停止十分钟
time.sleep(5)
#点击开始按钮
#点击进样回收开始按钮
jinyanghuishoukaishiannuiX=
jinyanghuishoukaishiannuiY=
pyautogui.moveTo(jinyanghuishoukaishiannuiX,jinyanghuishoukaishiannuiY,0.5)
pyautogui.click(jinyanghuishoukaishiannuiX,jinyanghuishoukaishiannuiY)
#点击转换停止按钮
zhuanhuankaishiannuiX=
zhuanhuankaishiannuiY=
pyautogui.moveTo(zhuanhuankaishiannuiX,zhuanhuankaishiannuiY,0.5)
pyautogui.click(zhuanhuankaishiannuiX,zhuanhuankaishiannuiY)
#点击凝血仪1停止按钮
ningxueyi1kaishiannuiX=
ningxueyi1kaishiannuiY=
pyautogui.moveTo(ningxueyi1kaishiannuiX,ningxueyi1kaishiannuiY,0.5)
#点击凝血仪2停止按钮
ningxueyi1kaishiannui2X=
ningxueyi1kaishiannui2Y=
pyautogui.moveTo(ningxueyi1kaishiannui2X,ningxueyi1kaishiannui2Y,0.5)
pyautogui.click(ningxueyi1kaishiannui2X,ningxueyi1kaishiannui2Y)
#点击凝血仪3停止按钮
ningxueyi1kaishiannui3X=
ningxueyi1kaishiannui3Y=
pyautogui.moveTo(ningxueyi1kaishiannui3X,ningxueyi1kaishiannui3Y,0.5)
pyautogui.click(ningxueyi1kaishiannui3X,ningxueyi1kaishiannui3Y)
#点击缓存区模块停止按钮
huancunqukaishiannuiX=
huancunqukaishiannuiY=
pyautogui.moveTo(huancunqukaishiannuiX,huancunqukaishiannuiY,0.5)
pyautogui.click(huancunqukaishiannuiX,huancunqukaishiannuiY)
#凝血仪恢复模块
#停止5分钟
time.sleep(5)
#1
ningxueyituojianniu1X=
ningxueyituojianniu1Y=
pyautogui.moveTo(ningxueyituojianniu1X,ningxueyituojianniu1Y,0.5)
pyautogui.click(ningxueyituojianniu1X,ningxueyituojianniu1Y)
#2
ningxueyituojianniu2X=
ningxueyituojianniu2Y=
pyautogui.moveTo(ningxueyituojianniu2X,ningxueyituojianniu2Y,0.5)
pyautogui.click(ningxueyituojianniu2X,ningxueyituojianniu2Y)
#3
ningxueyituojianniu3X=
ningxueyituojianniu3Y=
pyautogui.moveTo(ningxueyituojianniu3X,ningxueyituojianniu3Y,0.5)
pyautogui.click(ningxueyituojianniu3X,ningxueyituojianniu3Y)
#停止5分钟
#凝血仪恢复模块
time.sleep(5)
#1
ningxueyihuifuanniu1X=
ningxueyihuifuanniu1Y=
pyautogui.moveTo(ningxueyihuifuanniu1X,ningxueyihuifuanniu1Y,0.5)
pyautogui.click(ningxueyihuifuanniu1X,ningxueyihuifuanniu1Y)
#2
ningxueyihuifuanniu2X=
ningxueyihuifuanniu2Y=
pyautogui.moveTo(ningxueyihuifuanniu2X,ningxueyihuifuanniu2Y,0.5)
pyautogui.click(ningxueyihuifuanniu2X,ningxueyihuifuanniu2Y)
#3
ningxueyihuifuanniu3X=
ningxueyihuifuanniu3Y=
pyautogui.moveTo(ningxueyihuifuanniu3X,ningxueyihuifuanniu3Y,0.5    )
pyautogui.click(ningxueyihuifuanniu3X,ningxueyihuifuanniu3Y)
